version: '2'
services:
  worker:
    image: gitmaya
    volumes:
      - .env:/server/.env
    command: celery -A tasks.celery worker -l DEBUG -c 2

  beat:
    extends: worker
    command: celery -A tasks.celery beat -l DEBUG

  gitmaya:
    extends: worker
    ports:
      - "8888"
    environment:
      - VIRTUAL_HOST=api.gitmaya.com

  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --save 20 1 --loglevel warning

  rabbitmq:
    restart: always
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
      VIRTUAL_HOST: rabbitmq.gitmaya.com
      VIRTUAL_PORT: 15672
    ports:
      - "15672"
      - "5672"
    volumes:
      - ./data/rabbitmq:/data/mnesia

  mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 'gitmaya'
      MYSQL_DATABASE: 'gitmaya2023'
      TZ: 'Asia/Shanghai'
    ports:
      - "3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./dist:/var/www/html:ro
