version: '2'
services:
  worker:
    image: connectai/gitmaya
    volumes:
      - .env:/server/.env
    command: celery -A tasks.celery worker -l DEBUG -c 2

  beat:
    extends: worker
    command: celery -A tasks.celery beat -l DEBUG

  flower:
    extends: worker
    command: bash -c 'pip install flower && celery -A tasks.celery flower --basic-auth="gitmaya:gitmaya2023"'
    ports:
      - "5555"
    environment:
      - VIRTUAL_HOST=flower.gitmaya.com

  gitmaya:
    extends: worker
    ports:
      - "8888"
    environment:
      - VIRTUAL_HOST=gitmaya.com
    command: gunicorn --worker-class=gevent --workers 1 --bind 0.0.0.0:8888 -t 600 --keep-alive 60 --log-level=debug server:app

  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --save 20 1 --loglevel warning

  mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 'gitmaya2023'
      MYSQL_DATABASE: 'gitmaya'
      TZ: 'Asia/Shanghai'
    ports:
      - "3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

  proxy:
    image: connectai/gitmaya-proxy
    ports:
      - "8000:80"
      - "8001:81"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
