from parser import *

from chat_action_choose import *
from chat_action_result import *
from chat_manual import *
from chat_tip_failed import *
from issue_card import *
from issue_manual_help import *
from issue_open_in_browser import *
from issue_tip_failed import *
from issue_tip_success import *
from manage_fail import *
from manage_manual import *
from manage_repo_detect import *
from manage_success import *
from pr_card import *
from pr_manual import *
from pr_tip_commit_history import *
from pr_tip_failed import *
from pr_tip_success import *
