name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-main-app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_ACCOUNT }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push main app Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deploy/Dockerfile
        push: true
        tags: connectai/gitmaya:latest
